server:
  port: 8082

spring:
  application:
    name: carrito-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/carrito-service?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
