spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://localhost:8888
  profiles:
    active: native

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
